// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1HostsCveIPParams creates a new GetV1HostsCveIPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1HostsCveIPParams() *GetV1HostsCveIPParams {
	return &GetV1HostsCveIPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1HostsCveIPParamsWithTimeout creates a new GetV1HostsCveIPParams object
// with the ability to set a timeout on a request.
func NewGetV1HostsCveIPParamsWithTimeout(timeout time.Duration) *GetV1HostsCveIPParams {
	return &GetV1HostsCveIPParams{
		timeout: timeout,
	}
}

// NewGetV1HostsCveIPParamsWithContext creates a new GetV1HostsCveIPParams object
// with the ability to set a context for a request.
func NewGetV1HostsCveIPParamsWithContext(ctx context.Context) *GetV1HostsCveIPParams {
	return &GetV1HostsCveIPParams{
		Context: ctx,
	}
}

// NewGetV1HostsCveIPParamsWithHTTPClient creates a new GetV1HostsCveIPParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1HostsCveIPParamsWithHTTPClient(client *http.Client) *GetV1HostsCveIPParams {
	return &GetV1HostsCveIPParams{
		HTTPClient: client,
	}
}

/*
GetV1HostsCveIPParams contains all the parameters to send to the API endpoint

	for the get v1 hosts cve IP operation.

	Typically these are written to a http.Request.
*/
type GetV1HostsCveIPParams struct {

	/* IP.

	   get the ip
	*/
	IP string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 hosts cve IP params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1HostsCveIPParams) WithDefaults() *GetV1HostsCveIPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 hosts cve IP params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1HostsCveIPParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 hosts cve IP params
func (o *GetV1HostsCveIPParams) WithTimeout(timeout time.Duration) *GetV1HostsCveIPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 hosts cve IP params
func (o *GetV1HostsCveIPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 hosts cve IP params
func (o *GetV1HostsCveIPParams) WithContext(ctx context.Context) *GetV1HostsCveIPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 hosts cve IP params
func (o *GetV1HostsCveIPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 hosts cve IP params
func (o *GetV1HostsCveIPParams) WithHTTPClient(client *http.Client) *GetV1HostsCveIPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 hosts cve IP params
func (o *GetV1HostsCveIPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIP adds the ip to the get v1 hosts cve IP params
func (o *GetV1HostsCveIPParams) WithIP(ip string) *GetV1HostsCveIPParams {
	o.SetIP(ip)
	return o
}

// SetIP adds the ip to the get v1 hosts cve IP params
func (o *GetV1HostsCveIPParams) SetIP(ip string) {
	o.IP = ip
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1HostsCveIPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ip
	if err := r.SetPathParam("ip", o.IP); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
