// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1HostsCvesIPCveParams creates a new GetV1HostsCvesIPCveParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1HostsCvesIPCveParams() *GetV1HostsCvesIPCveParams {
	return &GetV1HostsCvesIPCveParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1HostsCvesIPCveParamsWithTimeout creates a new GetV1HostsCvesIPCveParams object
// with the ability to set a timeout on a request.
func NewGetV1HostsCvesIPCveParamsWithTimeout(timeout time.Duration) *GetV1HostsCvesIPCveParams {
	return &GetV1HostsCvesIPCveParams{
		timeout: timeout,
	}
}

// NewGetV1HostsCvesIPCveParamsWithContext creates a new GetV1HostsCvesIPCveParams object
// with the ability to set a context for a request.
func NewGetV1HostsCvesIPCveParamsWithContext(ctx context.Context) *GetV1HostsCvesIPCveParams {
	return &GetV1HostsCvesIPCveParams{
		Context: ctx,
	}
}

// NewGetV1HostsCvesIPCveParamsWithHTTPClient creates a new GetV1HostsCvesIPCveParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1HostsCvesIPCveParamsWithHTTPClient(client *http.Client) *GetV1HostsCvesIPCveParams {
	return &GetV1HostsCvesIPCveParams{
		HTTPClient: client,
	}
}

/*
GetV1HostsCvesIPCveParams contains all the parameters to send to the API endpoint

	for the get v1 hosts cves IP cve operation.

	Typically these are written to a http.Request.
*/
type GetV1HostsCvesIPCveParams struct {

	/* Cve.

	   cve id
	*/
	Cve string

	/* IP.

	   host ip ip
	*/
	IP string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 hosts cves IP cve params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1HostsCvesIPCveParams) WithDefaults() *GetV1HostsCvesIPCveParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 hosts cves IP cve params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1HostsCvesIPCveParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 hosts cves IP cve params
func (o *GetV1HostsCvesIPCveParams) WithTimeout(timeout time.Duration) *GetV1HostsCvesIPCveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 hosts cves IP cve params
func (o *GetV1HostsCvesIPCveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 hosts cves IP cve params
func (o *GetV1HostsCvesIPCveParams) WithContext(ctx context.Context) *GetV1HostsCvesIPCveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 hosts cves IP cve params
func (o *GetV1HostsCvesIPCveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 hosts cves IP cve params
func (o *GetV1HostsCvesIPCveParams) WithHTTPClient(client *http.Client) *GetV1HostsCvesIPCveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 hosts cves IP cve params
func (o *GetV1HostsCvesIPCveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCve adds the cve to the get v1 hosts cves IP cve params
func (o *GetV1HostsCvesIPCveParams) WithCve(cve string) *GetV1HostsCvesIPCveParams {
	o.SetCve(cve)
	return o
}

// SetCve adds the cve to the get v1 hosts cves IP cve params
func (o *GetV1HostsCvesIPCveParams) SetCve(cve string) {
	o.Cve = cve
}

// WithIP adds the ip to the get v1 hosts cves IP cve params
func (o *GetV1HostsCvesIPCveParams) WithIP(ip string) *GetV1HostsCvesIPCveParams {
	o.SetIP(ip)
	return o
}

// SetIP adds the ip to the get v1 hosts cves IP cve params
func (o *GetV1HostsCvesIPCveParams) SetIP(ip string) {
	o.IP = ip
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1HostsCvesIPCveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cve
	if err := r.SetPathParam("cve", o.Cve); err != nil {
		return err
	}

	// path param ip
	if err := r.SetPathParam("ip", o.IP); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
