// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cybledev/odin-sdk-go/models"
)

// NewPostV1HostsSearchParams creates a new PostV1HostsSearchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1HostsSearchParams() *PostV1HostsSearchParams {
	return &PostV1HostsSearchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1HostsSearchParamsWithTimeout creates a new PostV1HostsSearchParams object
// with the ability to set a timeout on a request.
func NewPostV1HostsSearchParamsWithTimeout(timeout time.Duration) *PostV1HostsSearchParams {
	return &PostV1HostsSearchParams{
		timeout: timeout,
	}
}

// NewPostV1HostsSearchParamsWithContext creates a new PostV1HostsSearchParams object
// with the ability to set a context for a request.
func NewPostV1HostsSearchParamsWithContext(ctx context.Context) *PostV1HostsSearchParams {
	return &PostV1HostsSearchParams{
		Context: ctx,
	}
}

// NewPostV1HostsSearchParamsWithHTTPClient creates a new PostV1HostsSearchParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1HostsSearchParamsWithHTTPClient(client *http.Client) *PostV1HostsSearchParams {
	return &PostV1HostsSearchParams{
		HTTPClient: client,
	}
}

/*
PostV1HostsSearchParams contains all the parameters to send to the API endpoint

	for the post v1 hosts search operation.

	Typically these are written to a http.Request.
*/
type PostV1HostsSearchParams struct {

	/* Query.

	   Search Query
	*/
	Query *models.SearchRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1 hosts search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1HostsSearchParams) WithDefaults() *PostV1HostsSearchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1 hosts search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1HostsSearchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1 hosts search params
func (o *PostV1HostsSearchParams) WithTimeout(timeout time.Duration) *PostV1HostsSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 hosts search params
func (o *PostV1HostsSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 hosts search params
func (o *PostV1HostsSearchParams) WithContext(ctx context.Context) *PostV1HostsSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 hosts search params
func (o *PostV1HostsSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 hosts search params
func (o *PostV1HostsSearchParams) WithHTTPClient(client *http.Client) *PostV1HostsSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 hosts search params
func (o *PostV1HostsSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuery adds the query to the post v1 hosts search params
func (o *PostV1HostsSearchParams) WithQuery(query *models.SearchRequest) *PostV1HostsSearchParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the post v1 hosts search params
func (o *PostV1HostsSearchParams) SetQuery(query *models.SearchRequest) {
	o.Query = query
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1HostsSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Query != nil {
		if err := r.SetBodyParam(o.Query); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
