// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cybledev/odin-sdk-go/models"
)

// PostV1HostsSummaryReader is a Reader for the PostV1HostsSummary structure.
type PostV1HostsSummaryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1HostsSummaryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostV1HostsSummaryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostV1HostsSummaryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 402:
		result := NewPostV1HostsSummaryPaymentRequired()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 408:
		result := NewPostV1HostsSummaryRequestTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostV1HostsSummaryInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/hosts/summary] PostV1HostsSummary", response, response.Code())
	}
}

// NewPostV1HostsSummaryOK creates a PostV1HostsSummaryOK with default headers values
func NewPostV1HostsSummaryOK() *PostV1HostsSummaryOK {
	return &PostV1HostsSummaryOK{}
}

/*
PostV1HostsSummaryOK describes a response with status code 200, with default header values.

OK
*/
type PostV1HostsSummaryOK struct {
	Payload *models.IpservicesHostsSummaryResponse
}

// IsSuccess returns true when this post v1 hosts summary o k response has a 2xx status code
func (o *PostV1HostsSummaryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post v1 hosts summary o k response has a 3xx status code
func (o *PostV1HostsSummaryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 hosts summary o k response has a 4xx status code
func (o *PostV1HostsSummaryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post v1 hosts summary o k response has a 5xx status code
func (o *PostV1HostsSummaryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 hosts summary o k response a status code equal to that given
func (o *PostV1HostsSummaryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post v1 hosts summary o k response
func (o *PostV1HostsSummaryOK) Code() int {
	return 200
}

func (o *PostV1HostsSummaryOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/hosts/summary][%d] postV1HostsSummaryOK %s", 200, payload)
}

func (o *PostV1HostsSummaryOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/hosts/summary][%d] postV1HostsSummaryOK %s", 200, payload)
}

func (o *PostV1HostsSummaryOK) GetPayload() *models.IpservicesHostsSummaryResponse {
	return o.Payload
}

func (o *PostV1HostsSummaryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpservicesHostsSummaryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostV1HostsSummaryBadRequest creates a PostV1HostsSummaryBadRequest with default headers values
func NewPostV1HostsSummaryBadRequest() *PostV1HostsSummaryBadRequest {
	return &PostV1HostsSummaryBadRequest{}
}

/*
PostV1HostsSummaryBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostV1HostsSummaryBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this post v1 hosts summary bad request response has a 2xx status code
func (o *PostV1HostsSummaryBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post v1 hosts summary bad request response has a 3xx status code
func (o *PostV1HostsSummaryBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 hosts summary bad request response has a 4xx status code
func (o *PostV1HostsSummaryBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post v1 hosts summary bad request response has a 5xx status code
func (o *PostV1HostsSummaryBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 hosts summary bad request response a status code equal to that given
func (o *PostV1HostsSummaryBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post v1 hosts summary bad request response
func (o *PostV1HostsSummaryBadRequest) Code() int {
	return 400
}

func (o *PostV1HostsSummaryBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/hosts/summary][%d] postV1HostsSummaryBadRequest %s", 400, payload)
}

func (o *PostV1HostsSummaryBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/hosts/summary][%d] postV1HostsSummaryBadRequest %s", 400, payload)
}

func (o *PostV1HostsSummaryBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostV1HostsSummaryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostV1HostsSummaryPaymentRequired creates a PostV1HostsSummaryPaymentRequired with default headers values
func NewPostV1HostsSummaryPaymentRequired() *PostV1HostsSummaryPaymentRequired {
	return &PostV1HostsSummaryPaymentRequired{}
}

/*
PostV1HostsSummaryPaymentRequired describes a response with status code 402, with default header values.

Payment Required
*/
type PostV1HostsSummaryPaymentRequired struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this post v1 hosts summary payment required response has a 2xx status code
func (o *PostV1HostsSummaryPaymentRequired) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post v1 hosts summary payment required response has a 3xx status code
func (o *PostV1HostsSummaryPaymentRequired) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 hosts summary payment required response has a 4xx status code
func (o *PostV1HostsSummaryPaymentRequired) IsClientError() bool {
	return true
}

// IsServerError returns true when this post v1 hosts summary payment required response has a 5xx status code
func (o *PostV1HostsSummaryPaymentRequired) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 hosts summary payment required response a status code equal to that given
func (o *PostV1HostsSummaryPaymentRequired) IsCode(code int) bool {
	return code == 402
}

// Code gets the status code for the post v1 hosts summary payment required response
func (o *PostV1HostsSummaryPaymentRequired) Code() int {
	return 402
}

func (o *PostV1HostsSummaryPaymentRequired) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/hosts/summary][%d] postV1HostsSummaryPaymentRequired %s", 402, payload)
}

func (o *PostV1HostsSummaryPaymentRequired) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/hosts/summary][%d] postV1HostsSummaryPaymentRequired %s", 402, payload)
}

func (o *PostV1HostsSummaryPaymentRequired) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostV1HostsSummaryPaymentRequired) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostV1HostsSummaryRequestTimeout creates a PostV1HostsSummaryRequestTimeout with default headers values
func NewPostV1HostsSummaryRequestTimeout() *PostV1HostsSummaryRequestTimeout {
	return &PostV1HostsSummaryRequestTimeout{}
}

/*
PostV1HostsSummaryRequestTimeout describes a response with status code 408, with default header values.

Request Timeout
*/
type PostV1HostsSummaryRequestTimeout struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this post v1 hosts summary request timeout response has a 2xx status code
func (o *PostV1HostsSummaryRequestTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post v1 hosts summary request timeout response has a 3xx status code
func (o *PostV1HostsSummaryRequestTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 hosts summary request timeout response has a 4xx status code
func (o *PostV1HostsSummaryRequestTimeout) IsClientError() bool {
	return true
}

// IsServerError returns true when this post v1 hosts summary request timeout response has a 5xx status code
func (o *PostV1HostsSummaryRequestTimeout) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 hosts summary request timeout response a status code equal to that given
func (o *PostV1HostsSummaryRequestTimeout) IsCode(code int) bool {
	return code == 408
}

// Code gets the status code for the post v1 hosts summary request timeout response
func (o *PostV1HostsSummaryRequestTimeout) Code() int {
	return 408
}

func (o *PostV1HostsSummaryRequestTimeout) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/hosts/summary][%d] postV1HostsSummaryRequestTimeout %s", 408, payload)
}

func (o *PostV1HostsSummaryRequestTimeout) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/hosts/summary][%d] postV1HostsSummaryRequestTimeout %s", 408, payload)
}

func (o *PostV1HostsSummaryRequestTimeout) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostV1HostsSummaryRequestTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostV1HostsSummaryInternalServerError creates a PostV1HostsSummaryInternalServerError with default headers values
func NewPostV1HostsSummaryInternalServerError() *PostV1HostsSummaryInternalServerError {
	return &PostV1HostsSummaryInternalServerError{}
}

/*
PostV1HostsSummaryInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostV1HostsSummaryInternalServerError struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this post v1 hosts summary internal server error response has a 2xx status code
func (o *PostV1HostsSummaryInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post v1 hosts summary internal server error response has a 3xx status code
func (o *PostV1HostsSummaryInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 hosts summary internal server error response has a 4xx status code
func (o *PostV1HostsSummaryInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post v1 hosts summary internal server error response has a 5xx status code
func (o *PostV1HostsSummaryInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post v1 hosts summary internal server error response a status code equal to that given
func (o *PostV1HostsSummaryInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post v1 hosts summary internal server error response
func (o *PostV1HostsSummaryInternalServerError) Code() int {
	return 500
}

func (o *PostV1HostsSummaryInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/hosts/summary][%d] postV1HostsSummaryInternalServerError %s", 500, payload)
}

func (o *PostV1HostsSummaryInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/hosts/summary][%d] postV1HostsSummaryInternalServerError %s", 500, payload)
}

func (o *PostV1HostsSummaryInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostV1HostsSummaryInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
