// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cybledev/odin-sdk-go/models"
)

// NewPostV1HostsCountParams creates a new PostV1HostsCountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1HostsCountParams() *PostV1HostsCountParams {
	return &PostV1HostsCountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1HostsCountParamsWithTimeout creates a new PostV1HostsCountParams object
// with the ability to set a timeout on a request.
func NewPostV1HostsCountParamsWithTimeout(timeout time.Duration) *PostV1HostsCountParams {
	return &PostV1HostsCountParams{
		timeout: timeout,
	}
}

// NewPostV1HostsCountParamsWithContext creates a new PostV1HostsCountParams object
// with the ability to set a context for a request.
func NewPostV1HostsCountParamsWithContext(ctx context.Context) *PostV1HostsCountParams {
	return &PostV1HostsCountParams{
		Context: ctx,
	}
}

// NewPostV1HostsCountParamsWithHTTPClient creates a new PostV1HostsCountParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1HostsCountParamsWithHTTPClient(client *http.Client) *PostV1HostsCountParams {
	return &PostV1HostsCountParams{
		HTTPClient: client,
	}
}

/*
PostV1HostsCountParams contains all the parameters to send to the API endpoint

	for the post v1 hosts count operation.

	Typically these are written to a http.Request.
*/
type PostV1HostsCountParams struct {

	/* Query.

	   Count Query
	*/
	Query *models.CountRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1 hosts count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1HostsCountParams) WithDefaults() *PostV1HostsCountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1 hosts count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1HostsCountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1 hosts count params
func (o *PostV1HostsCountParams) WithTimeout(timeout time.Duration) *PostV1HostsCountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 hosts count params
func (o *PostV1HostsCountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 hosts count params
func (o *PostV1HostsCountParams) WithContext(ctx context.Context) *PostV1HostsCountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 hosts count params
func (o *PostV1HostsCountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 hosts count params
func (o *PostV1HostsCountParams) WithHTTPClient(client *http.Client) *PostV1HostsCountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 hosts count params
func (o *PostV1HostsCountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuery adds the query to the post v1 hosts count params
func (o *PostV1HostsCountParams) WithQuery(query *models.CountRequest) *PostV1HostsCountParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the post v1 hosts count params
func (o *PostV1HostsCountParams) SetQuery(query *models.CountRequest) {
	o.Query = query
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1HostsCountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Query != nil {
		if err := r.SetBodyParam(o.Query); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
