// Code generated by go-swagger; DO NOT EDIT.

package certificate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cybledev/odin-sdk-go/models"
)

// NewPostV1CertificatesScrollParams creates a new PostV1CertificatesScrollParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1CertificatesScrollParams() *PostV1CertificatesScrollParams {
	return &PostV1CertificatesScrollParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1CertificatesScrollParamsWithTimeout creates a new PostV1CertificatesScrollParams object
// with the ability to set a timeout on a request.
func NewPostV1CertificatesScrollParamsWithTimeout(timeout time.Duration) *PostV1CertificatesScrollParams {
	return &PostV1CertificatesScrollParams{
		timeout: timeout,
	}
}

// NewPostV1CertificatesScrollParamsWithContext creates a new PostV1CertificatesScrollParams object
// with the ability to set a context for a request.
func NewPostV1CertificatesScrollParamsWithContext(ctx context.Context) *PostV1CertificatesScrollParams {
	return &PostV1CertificatesScrollParams{
		Context: ctx,
	}
}

// NewPostV1CertificatesScrollParamsWithHTTPClient creates a new PostV1CertificatesScrollParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1CertificatesScrollParamsWithHTTPClient(client *http.Client) *PostV1CertificatesScrollParams {
	return &PostV1CertificatesScrollParams{
		HTTPClient: client,
	}
}

/*
PostV1CertificatesScrollParams contains all the parameters to send to the API endpoint

	for the post v1 certificates scroll operation.

	Typically these are written to a http.Request.
*/
type PostV1CertificatesScrollParams struct {

	/* Query.

	   Search Query
	*/
	Query *models.CertificateCertScrollRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1 certificates scroll params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1CertificatesScrollParams) WithDefaults() *PostV1CertificatesScrollParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1 certificates scroll params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1CertificatesScrollParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1 certificates scroll params
func (o *PostV1CertificatesScrollParams) WithTimeout(timeout time.Duration) *PostV1CertificatesScrollParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 certificates scroll params
func (o *PostV1CertificatesScrollParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 certificates scroll params
func (o *PostV1CertificatesScrollParams) WithContext(ctx context.Context) *PostV1CertificatesScrollParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 certificates scroll params
func (o *PostV1CertificatesScrollParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 certificates scroll params
func (o *PostV1CertificatesScrollParams) WithHTTPClient(client *http.Client) *PostV1CertificatesScrollParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 certificates scroll params
func (o *PostV1CertificatesScrollParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuery adds the query to the post v1 certificates scroll params
func (o *PostV1CertificatesScrollParams) WithQuery(query *models.CertificateCertScrollRequest) *PostV1CertificatesScrollParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the post v1 certificates scroll params
func (o *PostV1CertificatesScrollParams) SetQuery(query *models.CertificateCertScrollRequest) {
	o.Query = query
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1CertificatesScrollParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Query != nil {
		if err := r.SetBodyParam(o.Query); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
