// Code generated by go-swagger; DO NOT EDIT.

package certificate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cybledev/odin-sdk-go/models"
)

// NewPostV1CertificatesScrollNextParams creates a new PostV1CertificatesScrollNextParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1CertificatesScrollNextParams() *PostV1CertificatesScrollNextParams {
	return &PostV1CertificatesScrollNextParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1CertificatesScrollNextParamsWithTimeout creates a new PostV1CertificatesScrollNextParams object
// with the ability to set a timeout on a request.
func NewPostV1CertificatesScrollNextParamsWithTimeout(timeout time.Duration) *PostV1CertificatesScrollNextParams {
	return &PostV1CertificatesScrollNextParams{
		timeout: timeout,
	}
}

// NewPostV1CertificatesScrollNextParamsWithContext creates a new PostV1CertificatesScrollNextParams object
// with the ability to set a context for a request.
func NewPostV1CertificatesScrollNextParamsWithContext(ctx context.Context) *PostV1CertificatesScrollNextParams {
	return &PostV1CertificatesScrollNextParams{
		Context: ctx,
	}
}

// NewPostV1CertificatesScrollNextParamsWithHTTPClient creates a new PostV1CertificatesScrollNextParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1CertificatesScrollNextParamsWithHTTPClient(client *http.Client) *PostV1CertificatesScrollNextParams {
	return &PostV1CertificatesScrollNextParams{
		HTTPClient: client,
	}
}

/*
PostV1CertificatesScrollNextParams contains all the parameters to send to the API endpoint

	for the post v1 certificates scroll next operation.

	Typically these are written to a http.Request.
*/
type PostV1CertificatesScrollNextParams struct {

	/* Query.

	   Search Query
	*/
	Query *models.CertificateNextBatchRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1 certificates scroll next params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1CertificatesScrollNextParams) WithDefaults() *PostV1CertificatesScrollNextParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1 certificates scroll next params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1CertificatesScrollNextParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1 certificates scroll next params
func (o *PostV1CertificatesScrollNextParams) WithTimeout(timeout time.Duration) *PostV1CertificatesScrollNextParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 certificates scroll next params
func (o *PostV1CertificatesScrollNextParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 certificates scroll next params
func (o *PostV1CertificatesScrollNextParams) WithContext(ctx context.Context) *PostV1CertificatesScrollNextParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 certificates scroll next params
func (o *PostV1CertificatesScrollNextParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 certificates scroll next params
func (o *PostV1CertificatesScrollNextParams) WithHTTPClient(client *http.Client) *PostV1CertificatesScrollNextParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 certificates scroll next params
func (o *PostV1CertificatesScrollNextParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuery adds the query to the post v1 certificates scroll next params
func (o *PostV1CertificatesScrollNextParams) WithQuery(query *models.CertificateNextBatchRequest) *PostV1CertificatesScrollNextParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the post v1 certificates scroll next params
func (o *PostV1CertificatesScrollNextParams) SetQuery(query *models.CertificateNextBatchRequest) {
	o.Query = query
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1CertificatesScrollNextParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Query != nil {
		if err := r.SetBodyParam(o.Query); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
