// Code generated by go-swagger; DO NOT EDIT.

package exposed_files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cybledev/odin-sdk-go/models"
)

// NewPostV1ExposedFilesCountParams creates a new PostV1ExposedFilesCountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1ExposedFilesCountParams() *PostV1ExposedFilesCountParams {
	return &PostV1ExposedFilesCountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1ExposedFilesCountParamsWithTimeout creates a new PostV1ExposedFilesCountParams object
// with the ability to set a timeout on a request.
func NewPostV1ExposedFilesCountParamsWithTimeout(timeout time.Duration) *PostV1ExposedFilesCountParams {
	return &PostV1ExposedFilesCountParams{
		timeout: timeout,
	}
}

// NewPostV1ExposedFilesCountParamsWithContext creates a new PostV1ExposedFilesCountParams object
// with the ability to set a context for a request.
func NewPostV1ExposedFilesCountParamsWithContext(ctx context.Context) *PostV1ExposedFilesCountParams {
	return &PostV1ExposedFilesCountParams{
		Context: ctx,
	}
}

// NewPostV1ExposedFilesCountParamsWithHTTPClient creates a new PostV1ExposedFilesCountParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1ExposedFilesCountParamsWithHTTPClient(client *http.Client) *PostV1ExposedFilesCountParams {
	return &PostV1ExposedFilesCountParams{
		HTTPClient: client,
	}
}

/*
PostV1ExposedFilesCountParams contains all the parameters to send to the API endpoint

	for the post v1 exposed files count operation.

	Typically these are written to a http.Request.
*/
type PostV1ExposedFilesCountParams struct {

	/* Query.

	   Count Request
	*/
	Query *models.ExposedCountRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1 exposed files count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1ExposedFilesCountParams) WithDefaults() *PostV1ExposedFilesCountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1 exposed files count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1ExposedFilesCountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1 exposed files count params
func (o *PostV1ExposedFilesCountParams) WithTimeout(timeout time.Duration) *PostV1ExposedFilesCountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 exposed files count params
func (o *PostV1ExposedFilesCountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 exposed files count params
func (o *PostV1ExposedFilesCountParams) WithContext(ctx context.Context) *PostV1ExposedFilesCountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 exposed files count params
func (o *PostV1ExposedFilesCountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 exposed files count params
func (o *PostV1ExposedFilesCountParams) WithHTTPClient(client *http.Client) *PostV1ExposedFilesCountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 exposed files count params
func (o *PostV1ExposedFilesCountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuery adds the query to the post v1 exposed files count params
func (o *PostV1ExposedFilesCountParams) WithQuery(query *models.ExposedCountRequest) *PostV1ExposedFilesCountParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the post v1 exposed files count params
func (o *PostV1ExposedFilesCountParams) SetQuery(query *models.ExposedCountRequest) {
	o.Query = query
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1ExposedFilesCountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Query != nil {
		if err := r.SetBodyParam(o.Query); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
