// Code generated by go-swagger; DO NOT EDIT.

package exposed_buckets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cybledev/odin-sdk-go/models"
)

// NewPostV1ExposedBucketsCountParams creates a new PostV1ExposedBucketsCountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1ExposedBucketsCountParams() *PostV1ExposedBucketsCountParams {
	return &PostV1ExposedBucketsCountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1ExposedBucketsCountParamsWithTimeout creates a new PostV1ExposedBucketsCountParams object
// with the ability to set a timeout on a request.
func NewPostV1ExposedBucketsCountParamsWithTimeout(timeout time.Duration) *PostV1ExposedBucketsCountParams {
	return &PostV1ExposedBucketsCountParams{
		timeout: timeout,
	}
}

// NewPostV1ExposedBucketsCountParamsWithContext creates a new PostV1ExposedBucketsCountParams object
// with the ability to set a context for a request.
func NewPostV1ExposedBucketsCountParamsWithContext(ctx context.Context) *PostV1ExposedBucketsCountParams {
	return &PostV1ExposedBucketsCountParams{
		Context: ctx,
	}
}

// NewPostV1ExposedBucketsCountParamsWithHTTPClient creates a new PostV1ExposedBucketsCountParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1ExposedBucketsCountParamsWithHTTPClient(client *http.Client) *PostV1ExposedBucketsCountParams {
	return &PostV1ExposedBucketsCountParams{
		HTTPClient: client,
	}
}

/*
PostV1ExposedBucketsCountParams contains all the parameters to send to the API endpoint

	for the post v1 exposed buckets count operation.

	Typically these are written to a http.Request.
*/
type PostV1ExposedBucketsCountParams struct {

	/* Query.

	   Count Request
	*/
	Query *models.ExposedCountRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1 exposed buckets count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1ExposedBucketsCountParams) WithDefaults() *PostV1ExposedBucketsCountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1 exposed buckets count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1ExposedBucketsCountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1 exposed buckets count params
func (o *PostV1ExposedBucketsCountParams) WithTimeout(timeout time.Duration) *PostV1ExposedBucketsCountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 exposed buckets count params
func (o *PostV1ExposedBucketsCountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 exposed buckets count params
func (o *PostV1ExposedBucketsCountParams) WithContext(ctx context.Context) *PostV1ExposedBucketsCountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 exposed buckets count params
func (o *PostV1ExposedBucketsCountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 exposed buckets count params
func (o *PostV1ExposedBucketsCountParams) WithHTTPClient(client *http.Client) *PostV1ExposedBucketsCountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 exposed buckets count params
func (o *PostV1ExposedBucketsCountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuery adds the query to the post v1 exposed buckets count params
func (o *PostV1ExposedBucketsCountParams) WithQuery(query *models.ExposedCountRequest) *PostV1ExposedBucketsCountParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the post v1 exposed buckets count params
func (o *PostV1ExposedBucketsCountParams) SetQuery(query *models.ExposedCountRequest) {
	o.Query = query
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1ExposedBucketsCountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Query != nil {
		if err := r.SetBodyParam(o.Query); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
