// Code generated by go-swagger; DO NOT EDIT.

package domain

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/cybledev/odin-sdk-go/models"
)

// GetV1DomainWhoisDomainNameIsExpiredReader is a Reader for the GetV1DomainWhoisDomainNameIsExpired structure.
type GetV1DomainWhoisDomainNameIsExpiredReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1DomainWhoisDomainNameIsExpiredReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1DomainWhoisDomainNameIsExpiredOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetV1DomainWhoisDomainNameIsExpiredBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 402:
		result := NewGetV1DomainWhoisDomainNameIsExpiredPaymentRequired()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 408:
		result := NewGetV1DomainWhoisDomainNameIsExpiredRequestTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetV1DomainWhoisDomainNameIsExpiredInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/domain/whois/{domain-name}/is-expired] GetV1DomainWhoisDomainNameIsExpired", response, response.Code())
	}
}

// NewGetV1DomainWhoisDomainNameIsExpiredOK creates a GetV1DomainWhoisDomainNameIsExpiredOK with default headers values
func NewGetV1DomainWhoisDomainNameIsExpiredOK() *GetV1DomainWhoisDomainNameIsExpiredOK {
	return &GetV1DomainWhoisDomainNameIsExpiredOK{}
}

/*
GetV1DomainWhoisDomainNameIsExpiredOK describes a response with status code 200, with default header values.

OK
*/
type GetV1DomainWhoisDomainNameIsExpiredOK struct {
	Payload *GetV1DomainWhoisDomainNameIsExpiredOKBody
}

// IsSuccess returns true when this get v1 domain whois domain name is expired o k response has a 2xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 domain whois domain name is expired o k response has a 3xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 domain whois domain name is expired o k response has a 4xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 domain whois domain name is expired o k response has a 5xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 domain whois domain name is expired o k response a status code equal to that given
func (o *GetV1DomainWhoisDomainNameIsExpiredOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 domain whois domain name is expired o k response
func (o *GetV1DomainWhoisDomainNameIsExpiredOK) Code() int {
	return 200
}

func (o *GetV1DomainWhoisDomainNameIsExpiredOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/domain/whois/{domain-name}/is-expired][%d] getV1DomainWhoisDomainNameIsExpiredOK %s", 200, payload)
}

func (o *GetV1DomainWhoisDomainNameIsExpiredOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/domain/whois/{domain-name}/is-expired][%d] getV1DomainWhoisDomainNameIsExpiredOK %s", 200, payload)
}

func (o *GetV1DomainWhoisDomainNameIsExpiredOK) GetPayload() *GetV1DomainWhoisDomainNameIsExpiredOKBody {
	return o.Payload
}

func (o *GetV1DomainWhoisDomainNameIsExpiredOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetV1DomainWhoisDomainNameIsExpiredOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1DomainWhoisDomainNameIsExpiredBadRequest creates a GetV1DomainWhoisDomainNameIsExpiredBadRequest with default headers values
func NewGetV1DomainWhoisDomainNameIsExpiredBadRequest() *GetV1DomainWhoisDomainNameIsExpiredBadRequest {
	return &GetV1DomainWhoisDomainNameIsExpiredBadRequest{}
}

/*
GetV1DomainWhoisDomainNameIsExpiredBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetV1DomainWhoisDomainNameIsExpiredBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this get v1 domain whois domain name is expired bad request response has a 2xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 domain whois domain name is expired bad request response has a 3xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 domain whois domain name is expired bad request response has a 4xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 domain whois domain name is expired bad request response has a 5xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 domain whois domain name is expired bad request response a status code equal to that given
func (o *GetV1DomainWhoisDomainNameIsExpiredBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get v1 domain whois domain name is expired bad request response
func (o *GetV1DomainWhoisDomainNameIsExpiredBadRequest) Code() int {
	return 400
}

func (o *GetV1DomainWhoisDomainNameIsExpiredBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/domain/whois/{domain-name}/is-expired][%d] getV1DomainWhoisDomainNameIsExpiredBadRequest %s", 400, payload)
}

func (o *GetV1DomainWhoisDomainNameIsExpiredBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/domain/whois/{domain-name}/is-expired][%d] getV1DomainWhoisDomainNameIsExpiredBadRequest %s", 400, payload)
}

func (o *GetV1DomainWhoisDomainNameIsExpiredBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *GetV1DomainWhoisDomainNameIsExpiredBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1DomainWhoisDomainNameIsExpiredPaymentRequired creates a GetV1DomainWhoisDomainNameIsExpiredPaymentRequired with default headers values
func NewGetV1DomainWhoisDomainNameIsExpiredPaymentRequired() *GetV1DomainWhoisDomainNameIsExpiredPaymentRequired {
	return &GetV1DomainWhoisDomainNameIsExpiredPaymentRequired{}
}

/*
GetV1DomainWhoisDomainNameIsExpiredPaymentRequired describes a response with status code 402, with default header values.

Payment Required
*/
type GetV1DomainWhoisDomainNameIsExpiredPaymentRequired struct {
	Payload interface{}
}

// IsSuccess returns true when this get v1 domain whois domain name is expired payment required response has a 2xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredPaymentRequired) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 domain whois domain name is expired payment required response has a 3xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredPaymentRequired) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 domain whois domain name is expired payment required response has a 4xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredPaymentRequired) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 domain whois domain name is expired payment required response has a 5xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredPaymentRequired) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 domain whois domain name is expired payment required response a status code equal to that given
func (o *GetV1DomainWhoisDomainNameIsExpiredPaymentRequired) IsCode(code int) bool {
	return code == 402
}

// Code gets the status code for the get v1 domain whois domain name is expired payment required response
func (o *GetV1DomainWhoisDomainNameIsExpiredPaymentRequired) Code() int {
	return 402
}

func (o *GetV1DomainWhoisDomainNameIsExpiredPaymentRequired) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/domain/whois/{domain-name}/is-expired][%d] getV1DomainWhoisDomainNameIsExpiredPaymentRequired %s", 402, payload)
}

func (o *GetV1DomainWhoisDomainNameIsExpiredPaymentRequired) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/domain/whois/{domain-name}/is-expired][%d] getV1DomainWhoisDomainNameIsExpiredPaymentRequired %s", 402, payload)
}

func (o *GetV1DomainWhoisDomainNameIsExpiredPaymentRequired) GetPayload() interface{} {
	return o.Payload
}

func (o *GetV1DomainWhoisDomainNameIsExpiredPaymentRequired) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1DomainWhoisDomainNameIsExpiredRequestTimeout creates a GetV1DomainWhoisDomainNameIsExpiredRequestTimeout with default headers values
func NewGetV1DomainWhoisDomainNameIsExpiredRequestTimeout() *GetV1DomainWhoisDomainNameIsExpiredRequestTimeout {
	return &GetV1DomainWhoisDomainNameIsExpiredRequestTimeout{}
}

/*
GetV1DomainWhoisDomainNameIsExpiredRequestTimeout describes a response with status code 408, with default header values.

Request Timeout
*/
type GetV1DomainWhoisDomainNameIsExpiredRequestTimeout struct {
	Payload interface{}
}

// IsSuccess returns true when this get v1 domain whois domain name is expired request timeout response has a 2xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredRequestTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 domain whois domain name is expired request timeout response has a 3xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredRequestTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 domain whois domain name is expired request timeout response has a 4xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredRequestTimeout) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 domain whois domain name is expired request timeout response has a 5xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredRequestTimeout) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 domain whois domain name is expired request timeout response a status code equal to that given
func (o *GetV1DomainWhoisDomainNameIsExpiredRequestTimeout) IsCode(code int) bool {
	return code == 408
}

// Code gets the status code for the get v1 domain whois domain name is expired request timeout response
func (o *GetV1DomainWhoisDomainNameIsExpiredRequestTimeout) Code() int {
	return 408
}

func (o *GetV1DomainWhoisDomainNameIsExpiredRequestTimeout) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/domain/whois/{domain-name}/is-expired][%d] getV1DomainWhoisDomainNameIsExpiredRequestTimeout %s", 408, payload)
}

func (o *GetV1DomainWhoisDomainNameIsExpiredRequestTimeout) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/domain/whois/{domain-name}/is-expired][%d] getV1DomainWhoisDomainNameIsExpiredRequestTimeout %s", 408, payload)
}

func (o *GetV1DomainWhoisDomainNameIsExpiredRequestTimeout) GetPayload() interface{} {
	return o.Payload
}

func (o *GetV1DomainWhoisDomainNameIsExpiredRequestTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1DomainWhoisDomainNameIsExpiredInternalServerError creates a GetV1DomainWhoisDomainNameIsExpiredInternalServerError with default headers values
func NewGetV1DomainWhoisDomainNameIsExpiredInternalServerError() *GetV1DomainWhoisDomainNameIsExpiredInternalServerError {
	return &GetV1DomainWhoisDomainNameIsExpiredInternalServerError{}
}

/*
GetV1DomainWhoisDomainNameIsExpiredInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetV1DomainWhoisDomainNameIsExpiredInternalServerError struct {
	Payload interface{}
}

// IsSuccess returns true when this get v1 domain whois domain name is expired internal server error response has a 2xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 domain whois domain name is expired internal server error response has a 3xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 domain whois domain name is expired internal server error response has a 4xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 domain whois domain name is expired internal server error response has a 5xx status code
func (o *GetV1DomainWhoisDomainNameIsExpiredInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get v1 domain whois domain name is expired internal server error response a status code equal to that given
func (o *GetV1DomainWhoisDomainNameIsExpiredInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get v1 domain whois domain name is expired internal server error response
func (o *GetV1DomainWhoisDomainNameIsExpiredInternalServerError) Code() int {
	return 500
}

func (o *GetV1DomainWhoisDomainNameIsExpiredInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/domain/whois/{domain-name}/is-expired][%d] getV1DomainWhoisDomainNameIsExpiredInternalServerError %s", 500, payload)
}

func (o *GetV1DomainWhoisDomainNameIsExpiredInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/domain/whois/{domain-name}/is-expired][%d] getV1DomainWhoisDomainNameIsExpiredInternalServerError %s", 500, payload)
}

func (o *GetV1DomainWhoisDomainNameIsExpiredInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *GetV1DomainWhoisDomainNameIsExpiredInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetV1DomainWhoisDomainNameIsExpiredOKBody get v1 domain whois domain name is expired o k body
swagger:model GetV1DomainWhoisDomainNameIsExpiredOKBody
*/
type GetV1DomainWhoisDomainNameIsExpiredOKBody struct {
	models.SchemaAPIResponse

	// data
	Data []*models.SchemaDomainWhoisResponse `json:"data"`

	// meta
	Meta *models.SchemaPaginationMeta `json:"meta,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetV1DomainWhoisDomainNameIsExpiredOKBody) UnmarshalJSON(raw []byte) error {
	// GetV1DomainWhoisDomainNameIsExpiredOKBodyAO0
	var getV1DomainWhoisDomainNameIsExpiredOKBodyAO0 models.SchemaAPIResponse
	if err := swag.ReadJSON(raw, &getV1DomainWhoisDomainNameIsExpiredOKBodyAO0); err != nil {
		return err
	}
	o.SchemaAPIResponse = getV1DomainWhoisDomainNameIsExpiredOKBodyAO0

	// GetV1DomainWhoisDomainNameIsExpiredOKBodyAO1
	var dataGetV1DomainWhoisDomainNameIsExpiredOKBodyAO1 struct {
		Data []*models.SchemaDomainWhoisResponse `json:"data"`

		Meta *models.SchemaPaginationMeta `json:"meta,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataGetV1DomainWhoisDomainNameIsExpiredOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataGetV1DomainWhoisDomainNameIsExpiredOKBodyAO1.Data

	o.Meta = dataGetV1DomainWhoisDomainNameIsExpiredOKBodyAO1.Meta

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetV1DomainWhoisDomainNameIsExpiredOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getV1DomainWhoisDomainNameIsExpiredOKBodyAO0, err := swag.WriteJSON(o.SchemaAPIResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getV1DomainWhoisDomainNameIsExpiredOKBodyAO0)
	var dataGetV1DomainWhoisDomainNameIsExpiredOKBodyAO1 struct {
		Data []*models.SchemaDomainWhoisResponse `json:"data"`

		Meta *models.SchemaPaginationMeta `json:"meta,omitempty"`
	}

	dataGetV1DomainWhoisDomainNameIsExpiredOKBodyAO1.Data = o.Data

	dataGetV1DomainWhoisDomainNameIsExpiredOKBodyAO1.Meta = o.Meta

	jsonDataGetV1DomainWhoisDomainNameIsExpiredOKBodyAO1, errGetV1DomainWhoisDomainNameIsExpiredOKBodyAO1 := swag.WriteJSON(dataGetV1DomainWhoisDomainNameIsExpiredOKBodyAO1)
	if errGetV1DomainWhoisDomainNameIsExpiredOKBodyAO1 != nil {
		return nil, errGetV1DomainWhoisDomainNameIsExpiredOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetV1DomainWhoisDomainNameIsExpiredOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get v1 domain whois domain name is expired o k body
func (o *GetV1DomainWhoisDomainNameIsExpiredOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.SchemaAPIResponse
	if err := o.SchemaAPIResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMeta(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetV1DomainWhoisDomainNameIsExpiredOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getV1DomainWhoisDomainNameIsExpiredOK" + "." + "data" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getV1DomainWhoisDomainNameIsExpiredOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetV1DomainWhoisDomainNameIsExpiredOKBody) validateMeta(formats strfmt.Registry) error {

	if swag.IsZero(o.Meta) { // not required
		return nil
	}

	if o.Meta != nil {
		if err := o.Meta.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getV1DomainWhoisDomainNameIsExpiredOK" + "." + "meta")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getV1DomainWhoisDomainNameIsExpiredOK" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get v1 domain whois domain name is expired o k body based on the context it is used
func (o *GetV1DomainWhoisDomainNameIsExpiredOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.SchemaAPIResponse
	if err := o.SchemaAPIResponse.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateMeta(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetV1DomainWhoisDomainNameIsExpiredOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {

			if swag.IsZero(o.Data[i]) { // not required
				return nil
			}

			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getV1DomainWhoisDomainNameIsExpiredOK" + "." + "data" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getV1DomainWhoisDomainNameIsExpiredOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetV1DomainWhoisDomainNameIsExpiredOKBody) contextValidateMeta(ctx context.Context, formats strfmt.Registry) error {

	if o.Meta != nil {

		if swag.IsZero(o.Meta) { // not required
			return nil
		}

		if err := o.Meta.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getV1DomainWhoisDomainNameIsExpiredOK" + "." + "meta")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getV1DomainWhoisDomainNameIsExpiredOK" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetV1DomainWhoisDomainNameIsExpiredOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetV1DomainWhoisDomainNameIsExpiredOKBody) UnmarshalBinary(b []byte) error {
	var res GetV1DomainWhoisDomainNameIsExpiredOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
