// Code generated by go-swagger; DO NOT EDIT.

package domain

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1DomainWhoisDomainNameHistoricalParams creates a new GetV1DomainWhoisDomainNameHistoricalParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1DomainWhoisDomainNameHistoricalParams() *GetV1DomainWhoisDomainNameHistoricalParams {
	return &GetV1DomainWhoisDomainNameHistoricalParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1DomainWhoisDomainNameHistoricalParamsWithTimeout creates a new GetV1DomainWhoisDomainNameHistoricalParams object
// with the ability to set a timeout on a request.
func NewGetV1DomainWhoisDomainNameHistoricalParamsWithTimeout(timeout time.Duration) *GetV1DomainWhoisDomainNameHistoricalParams {
	return &GetV1DomainWhoisDomainNameHistoricalParams{
		timeout: timeout,
	}
}

// NewGetV1DomainWhoisDomainNameHistoricalParamsWithContext creates a new GetV1DomainWhoisDomainNameHistoricalParams object
// with the ability to set a context for a request.
func NewGetV1DomainWhoisDomainNameHistoricalParamsWithContext(ctx context.Context) *GetV1DomainWhoisDomainNameHistoricalParams {
	return &GetV1DomainWhoisDomainNameHistoricalParams{
		Context: ctx,
	}
}

// NewGetV1DomainWhoisDomainNameHistoricalParamsWithHTTPClient creates a new GetV1DomainWhoisDomainNameHistoricalParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1DomainWhoisDomainNameHistoricalParamsWithHTTPClient(client *http.Client) *GetV1DomainWhoisDomainNameHistoricalParams {
	return &GetV1DomainWhoisDomainNameHistoricalParams{
		HTTPClient: client,
	}
}

/*
GetV1DomainWhoisDomainNameHistoricalParams contains all the parameters to send to the API endpoint

	for the get v1 domain whois domain name historical operation.

	Typically these are written to a http.Request.
*/
type GetV1DomainWhoisDomainNameHistoricalParams struct {

	/* DomainName.

	   domain
	*/
	DomainName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 domain whois domain name historical params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1DomainWhoisDomainNameHistoricalParams) WithDefaults() *GetV1DomainWhoisDomainNameHistoricalParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 domain whois domain name historical params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1DomainWhoisDomainNameHistoricalParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 domain whois domain name historical params
func (o *GetV1DomainWhoisDomainNameHistoricalParams) WithTimeout(timeout time.Duration) *GetV1DomainWhoisDomainNameHistoricalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 domain whois domain name historical params
func (o *GetV1DomainWhoisDomainNameHistoricalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 domain whois domain name historical params
func (o *GetV1DomainWhoisDomainNameHistoricalParams) WithContext(ctx context.Context) *GetV1DomainWhoisDomainNameHistoricalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 domain whois domain name historical params
func (o *GetV1DomainWhoisDomainNameHistoricalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 domain whois domain name historical params
func (o *GetV1DomainWhoisDomainNameHistoricalParams) WithHTTPClient(client *http.Client) *GetV1DomainWhoisDomainNameHistoricalParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 domain whois domain name historical params
func (o *GetV1DomainWhoisDomainNameHistoricalParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomainName adds the domainName to the get v1 domain whois domain name historical params
func (o *GetV1DomainWhoisDomainNameHistoricalParams) WithDomainName(domainName string) *GetV1DomainWhoisDomainNameHistoricalParams {
	o.SetDomainName(domainName)
	return o
}

// SetDomainName adds the domainName to the get v1 domain whois domain name historical params
func (o *GetV1DomainWhoisDomainNameHistoricalParams) SetDomainName(domainName string) {
	o.DomainName = domainName
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1DomainWhoisDomainNameHistoricalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param domain-name
	if err := r.SetPathParam("domain-name", o.DomainName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
