// Code generated by go-swagger; DO NOT EDIT.

package domain

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1DomainWhoisDomainNameIsRegisteredParams creates a new GetV1DomainWhoisDomainNameIsRegisteredParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1DomainWhoisDomainNameIsRegisteredParams() *GetV1DomainWhoisDomainNameIsRegisteredParams {
	return &GetV1DomainWhoisDomainNameIsRegisteredParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1DomainWhoisDomainNameIsRegisteredParamsWithTimeout creates a new GetV1DomainWhoisDomainNameIsRegisteredParams object
// with the ability to set a timeout on a request.
func NewGetV1DomainWhoisDomainNameIsRegisteredParamsWithTimeout(timeout time.Duration) *GetV1DomainWhoisDomainNameIsRegisteredParams {
	return &GetV1DomainWhoisDomainNameIsRegisteredParams{
		timeout: timeout,
	}
}

// NewGetV1DomainWhoisDomainNameIsRegisteredParamsWithContext creates a new GetV1DomainWhoisDomainNameIsRegisteredParams object
// with the ability to set a context for a request.
func NewGetV1DomainWhoisDomainNameIsRegisteredParamsWithContext(ctx context.Context) *GetV1DomainWhoisDomainNameIsRegisteredParams {
	return &GetV1DomainWhoisDomainNameIsRegisteredParams{
		Context: ctx,
	}
}

// NewGetV1DomainWhoisDomainNameIsRegisteredParamsWithHTTPClient creates a new GetV1DomainWhoisDomainNameIsRegisteredParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1DomainWhoisDomainNameIsRegisteredParamsWithHTTPClient(client *http.Client) *GetV1DomainWhoisDomainNameIsRegisteredParams {
	return &GetV1DomainWhoisDomainNameIsRegisteredParams{
		HTTPClient: client,
	}
}

/*
GetV1DomainWhoisDomainNameIsRegisteredParams contains all the parameters to send to the API endpoint

	for the get v1 domain whois domain name is registered operation.

	Typically these are written to a http.Request.
*/
type GetV1DomainWhoisDomainNameIsRegisteredParams struct {

	/* DomainName.

	   domain
	*/
	DomainName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 domain whois domain name is registered params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1DomainWhoisDomainNameIsRegisteredParams) WithDefaults() *GetV1DomainWhoisDomainNameIsRegisteredParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 domain whois domain name is registered params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1DomainWhoisDomainNameIsRegisteredParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 domain whois domain name is registered params
func (o *GetV1DomainWhoisDomainNameIsRegisteredParams) WithTimeout(timeout time.Duration) *GetV1DomainWhoisDomainNameIsRegisteredParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 domain whois domain name is registered params
func (o *GetV1DomainWhoisDomainNameIsRegisteredParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 domain whois domain name is registered params
func (o *GetV1DomainWhoisDomainNameIsRegisteredParams) WithContext(ctx context.Context) *GetV1DomainWhoisDomainNameIsRegisteredParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 domain whois domain name is registered params
func (o *GetV1DomainWhoisDomainNameIsRegisteredParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 domain whois domain name is registered params
func (o *GetV1DomainWhoisDomainNameIsRegisteredParams) WithHTTPClient(client *http.Client) *GetV1DomainWhoisDomainNameIsRegisteredParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 domain whois domain name is registered params
func (o *GetV1DomainWhoisDomainNameIsRegisteredParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomainName adds the domainName to the get v1 domain whois domain name is registered params
func (o *GetV1DomainWhoisDomainNameIsRegisteredParams) WithDomainName(domainName string) *GetV1DomainWhoisDomainNameIsRegisteredParams {
	o.SetDomainName(domainName)
	return o
}

// SetDomainName adds the domainName to the get v1 domain whois domain name is registered params
func (o *GetV1DomainWhoisDomainNameIsRegisteredParams) SetDomainName(domainName string) {
	o.DomainName = domainName
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1DomainWhoisDomainNameIsRegisteredParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param domain-name
	if err := r.SetPathParam("domain-name", o.DomainName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
