// Code generated by go-swagger; DO NOT EDIT.

package domain

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cybledev/odin-sdk-go/models"
)

// NewPostV1DomainSubdomainSearchParams creates a new PostV1DomainSubdomainSearchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1DomainSubdomainSearchParams() *PostV1DomainSubdomainSearchParams {
	return &PostV1DomainSubdomainSearchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1DomainSubdomainSearchParamsWithTimeout creates a new PostV1DomainSubdomainSearchParams object
// with the ability to set a timeout on a request.
func NewPostV1DomainSubdomainSearchParamsWithTimeout(timeout time.Duration) *PostV1DomainSubdomainSearchParams {
	return &PostV1DomainSubdomainSearchParams{
		timeout: timeout,
	}
}

// NewPostV1DomainSubdomainSearchParamsWithContext creates a new PostV1DomainSubdomainSearchParams object
// with the ability to set a context for a request.
func NewPostV1DomainSubdomainSearchParamsWithContext(ctx context.Context) *PostV1DomainSubdomainSearchParams {
	return &PostV1DomainSubdomainSearchParams{
		Context: ctx,
	}
}

// NewPostV1DomainSubdomainSearchParamsWithHTTPClient creates a new PostV1DomainSubdomainSearchParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1DomainSubdomainSearchParamsWithHTTPClient(client *http.Client) *PostV1DomainSubdomainSearchParams {
	return &PostV1DomainSubdomainSearchParams{
		HTTPClient: client,
	}
}

/*
PostV1DomainSubdomainSearchParams contains all the parameters to send to the API endpoint

	for the post v1 domain subdomain search operation.

	Typically these are written to a http.Request.
*/
type PostV1DomainSubdomainSearchParams struct {

	/* Query.

	   Query
	*/
	Query *models.DNSDomainRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1 domain subdomain search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1DomainSubdomainSearchParams) WithDefaults() *PostV1DomainSubdomainSearchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1 domain subdomain search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1DomainSubdomainSearchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1 domain subdomain search params
func (o *PostV1DomainSubdomainSearchParams) WithTimeout(timeout time.Duration) *PostV1DomainSubdomainSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 domain subdomain search params
func (o *PostV1DomainSubdomainSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 domain subdomain search params
func (o *PostV1DomainSubdomainSearchParams) WithContext(ctx context.Context) *PostV1DomainSubdomainSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 domain subdomain search params
func (o *PostV1DomainSubdomainSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 domain subdomain search params
func (o *PostV1DomainSubdomainSearchParams) WithHTTPClient(client *http.Client) *PostV1DomainSubdomainSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 domain subdomain search params
func (o *PostV1DomainSubdomainSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuery adds the query to the post v1 domain subdomain search params
func (o *PostV1DomainSubdomainSearchParams) WithQuery(query *models.DNSDomainRequest) *PostV1DomainSubdomainSearchParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the post v1 domain subdomain search params
func (o *PostV1DomainSubdomainSearchParams) SetQuery(query *models.DNSDomainRequest) {
	o.Query = query
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1DomainSubdomainSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Query != nil {
		if err := r.SetBodyParam(o.Query); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
