// Code generated by go-swagger; DO NOT EDIT.

package domain

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cybledev/odin-sdk-go/models"
)

// NewPostV1DomainCountParams creates a new PostV1DomainCountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1DomainCountParams() *PostV1DomainCountParams {
	return &PostV1DomainCountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1DomainCountParamsWithTimeout creates a new PostV1DomainCountParams object
// with the ability to set a timeout on a request.
func NewPostV1DomainCountParamsWithTimeout(timeout time.Duration) *PostV1DomainCountParams {
	return &PostV1DomainCountParams{
		timeout: timeout,
	}
}

// NewPostV1DomainCountParamsWithContext creates a new PostV1DomainCountParams object
// with the ability to set a context for a request.
func NewPostV1DomainCountParamsWithContext(ctx context.Context) *PostV1DomainCountParams {
	return &PostV1DomainCountParams{
		Context: ctx,
	}
}

// NewPostV1DomainCountParamsWithHTTPClient creates a new PostV1DomainCountParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1DomainCountParamsWithHTTPClient(client *http.Client) *PostV1DomainCountParams {
	return &PostV1DomainCountParams{
		HTTPClient: client,
	}
}

/*
PostV1DomainCountParams contains all the parameters to send to the API endpoint

	for the post v1 domain count operation.

	Typically these are written to a http.Request.
*/
type PostV1DomainCountParams struct {

	/* Query.

	   Query
	*/
	Query *models.DNSDNSCountRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1 domain count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1DomainCountParams) WithDefaults() *PostV1DomainCountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1 domain count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1DomainCountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1 domain count params
func (o *PostV1DomainCountParams) WithTimeout(timeout time.Duration) *PostV1DomainCountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 domain count params
func (o *PostV1DomainCountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 domain count params
func (o *PostV1DomainCountParams) WithContext(ctx context.Context) *PostV1DomainCountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 domain count params
func (o *PostV1DomainCountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 domain count params
func (o *PostV1DomainCountParams) WithHTTPClient(client *http.Client) *PostV1DomainCountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 domain count params
func (o *PostV1DomainCountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuery adds the query to the post v1 domain count params
func (o *PostV1DomainCountParams) WithQuery(query *models.DNSDNSCountRequest) *PostV1DomainCountParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the post v1 domain count params
func (o *PostV1DomainCountParams) SetQuery(query *models.DNSDNSCountRequest) {
	o.Query = query
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1DomainCountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Query != nil {
		if err := r.SetBodyParam(o.Query); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
