// Code generated by go-swagger; DO NOT EDIT.

package fields

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1FieldsExposedBucketsParams creates a new GetV1FieldsExposedBucketsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1FieldsExposedBucketsParams() *GetV1FieldsExposedBucketsParams {
	return &GetV1FieldsExposedBucketsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1FieldsExposedBucketsParamsWithTimeout creates a new GetV1FieldsExposedBucketsParams object
// with the ability to set a timeout on a request.
func NewGetV1FieldsExposedBucketsParamsWithTimeout(timeout time.Duration) *GetV1FieldsExposedBucketsParams {
	return &GetV1FieldsExposedBucketsParams{
		timeout: timeout,
	}
}

// NewGetV1FieldsExposedBucketsParamsWithContext creates a new GetV1FieldsExposedBucketsParams object
// with the ability to set a context for a request.
func NewGetV1FieldsExposedBucketsParamsWithContext(ctx context.Context) *GetV1FieldsExposedBucketsParams {
	return &GetV1FieldsExposedBucketsParams{
		Context: ctx,
	}
}

// NewGetV1FieldsExposedBucketsParamsWithHTTPClient creates a new GetV1FieldsExposedBucketsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1FieldsExposedBucketsParamsWithHTTPClient(client *http.Client) *GetV1FieldsExposedBucketsParams {
	return &GetV1FieldsExposedBucketsParams{
		HTTPClient: client,
	}
}

/*
GetV1FieldsExposedBucketsParams contains all the parameters to send to the API endpoint

	for the get v1 fields exposed buckets operation.

	Typically these are written to a http.Request.
*/
type GetV1FieldsExposedBucketsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 fields exposed buckets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1FieldsExposedBucketsParams) WithDefaults() *GetV1FieldsExposedBucketsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 fields exposed buckets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1FieldsExposedBucketsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 fields exposed buckets params
func (o *GetV1FieldsExposedBucketsParams) WithTimeout(timeout time.Duration) *GetV1FieldsExposedBucketsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 fields exposed buckets params
func (o *GetV1FieldsExposedBucketsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 fields exposed buckets params
func (o *GetV1FieldsExposedBucketsParams) WithContext(ctx context.Context) *GetV1FieldsExposedBucketsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 fields exposed buckets params
func (o *GetV1FieldsExposedBucketsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 fields exposed buckets params
func (o *GetV1FieldsExposedBucketsParams) WithHTTPClient(client *http.Client) *GetV1FieldsExposedBucketsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 fields exposed buckets params
func (o *GetV1FieldsExposedBucketsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1FieldsExposedBucketsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
