// Code generated by go-swagger; DO NOT EDIT.

package fields

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1FieldsHostsCategoryParams creates a new GetV1FieldsHostsCategoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1FieldsHostsCategoryParams() *GetV1FieldsHostsCategoryParams {
	return &GetV1FieldsHostsCategoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1FieldsHostsCategoryParamsWithTimeout creates a new GetV1FieldsHostsCategoryParams object
// with the ability to set a timeout on a request.
func NewGetV1FieldsHostsCategoryParamsWithTimeout(timeout time.Duration) *GetV1FieldsHostsCategoryParams {
	return &GetV1FieldsHostsCategoryParams{
		timeout: timeout,
	}
}

// NewGetV1FieldsHostsCategoryParamsWithContext creates a new GetV1FieldsHostsCategoryParams object
// with the ability to set a context for a request.
func NewGetV1FieldsHostsCategoryParamsWithContext(ctx context.Context) *GetV1FieldsHostsCategoryParams {
	return &GetV1FieldsHostsCategoryParams{
		Context: ctx,
	}
}

// NewGetV1FieldsHostsCategoryParamsWithHTTPClient creates a new GetV1FieldsHostsCategoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1FieldsHostsCategoryParamsWithHTTPClient(client *http.Client) *GetV1FieldsHostsCategoryParams {
	return &GetV1FieldsHostsCategoryParams{
		HTTPClient: client,
	}
}

/*
GetV1FieldsHostsCategoryParams contains all the parameters to send to the API endpoint

	for the get v1 fields hosts category operation.

	Typically these are written to a http.Request.
*/
type GetV1FieldsHostsCategoryParams struct {

	/* Category.

	   get the category
	*/
	Category string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 fields hosts category params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1FieldsHostsCategoryParams) WithDefaults() *GetV1FieldsHostsCategoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 fields hosts category params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1FieldsHostsCategoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 fields hosts category params
func (o *GetV1FieldsHostsCategoryParams) WithTimeout(timeout time.Duration) *GetV1FieldsHostsCategoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 fields hosts category params
func (o *GetV1FieldsHostsCategoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 fields hosts category params
func (o *GetV1FieldsHostsCategoryParams) WithContext(ctx context.Context) *GetV1FieldsHostsCategoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 fields hosts category params
func (o *GetV1FieldsHostsCategoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 fields hosts category params
func (o *GetV1FieldsHostsCategoryParams) WithHTTPClient(client *http.Client) *GetV1FieldsHostsCategoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 fields hosts category params
func (o *GetV1FieldsHostsCategoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCategory adds the category to the get v1 fields hosts category params
func (o *GetV1FieldsHostsCategoryParams) WithCategory(category string) *GetV1FieldsHostsCategoryParams {
	o.SetCategory(category)
	return o
}

// SetCategory adds the category to the get v1 fields hosts category params
func (o *GetV1FieldsHostsCategoryParams) SetCategory(category string) {
	o.Category = category
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1FieldsHostsCategoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param category
	if err := r.SetPathParam("category", o.Category); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
